package org.laba.testing.gui.enums;

public enum NavElement {
  OVERVIEW,
  GETTINGSTARTED,
  PROJECTSTRUCTURE,
  CONFIGURATION,
  EXECUTION,
  AUTOMATIONWEB,
  AUTOMATIONMOBILE,
  AUTOMATIONAPI,
  AUTOMATIONWINDOWS,
  ADVANCEDDATABASE,
  ADVANCEDDATAPROVIDER,
  ADVANCEDDRIVER,
  ADVANCEDMOBILE,
  ADVANCEDLOCALIZATION,
  ADVANCEDPROGRAMFLOW,
  ADVANCEDPROXY,
  ADVANCEDSCREENSHOT,
  ADVANCEDSECURITY,
  INTEGRATIONZEBRUNNER,
  CUCUMBER,
  CONTRIBUTION
}
